[project]
name = "federated-model-watermark"
version = "0.1.0"
description = "联邦学习模型水印验证框架"
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name = "林裕斌" },
  { name = "曾科" },
  { name = "田承金" },
  { name = "吕善翔" }
]

[project.scripts]
federated_model_watermark = "federated_model_watermark.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}
